<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="9.9.0" />
    <PackageReference Include="OperationResultTools" Version="1.0.30" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.7" />
    <PackageReference Include="TinyHelpers" Version="3.3.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketMania.Clients\MarketMania.Clients.csproj" />
    <ProjectReference Include="..\MarketMania.Contracts\MarketMania.Contracts.csproj" />
    <ProjectReference Include="..\MarketMania.DataAccessLayer\MarketMania.DataAccessLayer.csproj" />
    <ProjectReference Include="..\MarketMania.Security\MarketMania.Security.csproj" />
    <ProjectReference Include="..\MarketMania.Shared\MarketMania.Shared.csproj" />
    <ProjectReference Include="..\MarketMania.StorageProviders\MarketMania.StorageProviders.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Messages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Messages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\TranslationResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TranslationResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Messages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Messages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TranslationResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>TranslationResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
